before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y binutils-dev libunwind8-dev curl gcc clang

language: rust

script:
  - rustup target add wasm32-unknown-unknown --toolchain nightly
  - cargo build

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true